<template>
  <section class="auth-page">
    <el-card shadow="never" v-loading="loading"><template #header><div class="head"><div><strong>{{ T('SMTPSettings') }}</strong><small>{{ T('SMTPSettingsDescription') }}</small></div><el-tag :type="hasPassword?'success':'info'">{{ hasPassword ? T('Configured') : T('NotConfigured') }}</el-tag></div></template><el-form label-position="top" class="form-grid"><el-form-item label="Host"><el-input v-model="smtpForm.host"/></el-form-item><el-form-item label="Port"><el-input-number v-model="smtpForm.port" :min="1" :max="65535"/></el-form-item><el-form-item :label="T('Username')"><el-input v-model="smtpForm.username"/></el-form-item><el-form-item :label="T('Password')"><el-input v-model="smtpForm.password" type="password" :placeholder="hasPassword?T('StoredSecretPlaceholder'):''" show-password/></el-form-item><el-form-item label="From"><el-input v-model="smtpForm.from"/></el-form-item><el-form-item label="TLS"><el-switch v-model="smtpForm.tls"/></el-form-item></el-form><div class="actions"><el-button type="primary" @click="save">{{ T('Save') }}</el-button><el-input v-model="testTo" :placeholder="T('TestRecipient')"/><el-button @click="sendTest">{{ T('SendTest') }}</el-button></div></el-card>
    <div class="auth-grid"><el-card shadow="never"><template #header><strong>{{ T('OIDCConnectionTest') }}</strong></template><el-input v-model="issuer" placeholder="https://id.example.com"/><el-button class="full" type="primary" plain @click="runOIDC">{{ T('TestConnection') }}</el-button><pre v-if="oidcResult">{{ JSON.stringify(oidcResult, null, 2) }}</pre></el-card><el-card shadow="never"><template #header><strong>{{ T('LDAPDryRun') }}</strong></template><el-input v-model="ldapUser" :placeholder="T('Username')"/><el-button class="full" type="primary" plain @click="runLDAP">{{ T('PreviewMapping') }}</el-button><pre v-if="ldapResult">{{ JSON.stringify(ldapResult, null, 2) }}</pre></el-card></div>
    <el-card shadow="never"><template #header><strong>{{ T('InviteUser') }}</strong></template><div class="actions"><el-input v-model="inviteForm.username" :placeholder="T('Username')"/><el-input v-model="inviteForm.email" :placeholder="T('Email')"/><el-button type="primary" @click="sendInvite">{{ T('SendInvite') }}</el-button></div></el-card>
  </section>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { notify as ElMessage } from '@/utils/notifications';
 import { dryRunLDAP, invite, saveSMTP, smtp, testOIDC, testSMTP } from '@/api/externalAuth'; import { T } from '@/utils/i18n'
const loading=ref(false),hasPassword=ref(false),testTo=ref(''),issuer=ref(''),ldapUser=ref(''),oidcResult=ref(null),ldapResult=ref(null);const smtpForm=reactive({host:'',port:587,username:'',password:'',from:'',tls:false});const inviteForm=reactive({username:'',email:''})
const load=async()=>{loading.value=true;const res=await smtp().catch(()=>false);if(res){Object.assign(smtpForm,res.data.setting);hasPassword.value=res.data.has_password}loading.value=false}
const save=async()=>{if(await saveSMTP(smtpForm).catch(()=>false)){ElMessage.success(T('Saved'));smtpForm.password='';load()}}
const sendTest=async()=>{if(await testSMTP({to:testTo.value}).catch(()=>false))ElMessage.success(T('TestMailSent'))}
const runOIDC=async()=>{const res=await testOIDC({issuer:issuer.value}).catch(()=>false);oidcResult.value=res?.data||null}
const runLDAP=async()=>{const res=await dryRunLDAP({username:ldapUser.value}).catch(()=>false);ldapResult.value=res?.data||null}
const sendInvite=async()=>{if(await invite(inviteForm).catch(()=>false))ElMessage.success(T('InviteSent'))}
onMounted(load)
</script>
<style scoped lang="scss">.auth-page{display:grid;gap:14px}.head{display:flex;align-items:center;justify-content:space-between;gap:12px}.head strong,.head small{display:block}.head small{margin-top:3px;color:var(--console-muted)}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.actions{display:flex;align-items:center;gap:10px}.auth-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{width:100%;margin-top:12px}pre{overflow:auto;max-height:260px;padding:12px;background:var(--console-canvas);border-radius:5px}@media(max-width:760px){.form-grid,.auth-grid{grid-template-columns:1fr}.actions{align-items:stretch;flex-direction:column}}</style>

